language: csharp
mono: none
dotnet: 2.2.101
dist: xenial
sudo: required
os:
  - linux
  - osx

# only build PRs and master
branches:
  only:
  - master

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install avahi-daemon       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo lsof -i :5353                      ; fi

script:
  - dotnet build -c Release --framework netstandard2 ./src
  - dotnet test  -c Release --framework netcoreapp2 ./test --filter TestCategory!=IPv6
  - dotnet test  -c Release --framework netcoreapp2.1 ./test --filter TestCategory!=IPv6
  - dotnet test  -c Release --framework netcoreapp2.2 ./test --filter TestCategory!=IPv6
