# gitversion will change the version number
version: x-{build}
branches:
  only:
   - master
configuration: Release
os: Visual Studio 2017

init:
  - git config --global core.autocrlf input
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:git_token):x-oauth-basic@github.com`n"
  - git config --global user.email "noreply@emanon.org"
  - git config --global user.name "Appveyor CI"

environment:
  git_token:
    secure: NeX5NCOUXsCLc1UjTJjqB9F02FZ8Wq0VsxqTXC8kBdyK6zjxjebrf/9Da2sY1Kql
  COVERALLS_REPO_TOKEN:
    secure: mxSBDkT22JU2Md+CSLG59sp0CqfE2f9RjqOn7XTPaIn2Jo2RNAFpSD+iZ0x0jh1J
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

# tools we need for bulding/testing/deploying
install:
   - choco install gitversion.portable -y
   - choco install docfx -y
   - npm install gh-pages -g

# gitversion will change the assembly info
pull_requests:
  do_not_increment_build_number: true

before_build:
  - ps: gitversion /output buildserver >gitversion.log

build_script:
  - dotnet build -c %CONFIGURATION% -p:Version=%GitVersion_MajorMinorPatch% -p:AssemblyVersion=%GitVersion_MajorMinorPatch%
  - dotnet pack -c %CONFIGURATION% --no-build --no-restore -p:Version=%GitVersion_MajorMinorPatch% -p:AssemblyVersion=%GitVersion_MajorMinorPatch%

after_build:
  - cmd: appveyor PushArtifact "src\bin\%CONFIGURATION%\Makaretu.Dns.Multicast.%GitVersion_MajorMinorPatch%.nupkg"

test_script:
  - dotnet test -c %CONFIGURATION% --no-build --no-restore test --filter TestCategory!=IPv6

after_test: 
# Generate coverage report
    - dotnet test -c %CONFIGURATION% -f netcoreapp2.2 test 
      --filter TestCategory!=IPv6 
      /p:CopyLocalLockFileAssemblies=true
      /p:CollectCoverage=true /p:Include="[Makaretu.Dns.Multicast]*"
    - choco install codecov -y
    - codecov -f "test/coverage.opencover.xml"
    - dotnet tool install --global coveralls.net --version 1.0.0
    - if defined COVERALLS_REPO_TOKEN
        csmacnz.coveralls.exe
        --opencover -i test/coverage.opencover.xml --useRelativePaths --serviceName appveyor --jobId %APPVEYOR_BUILD_NUMBER%

# Build documentation in doc\_site
    - docfx doc\docfx.json --logLevel Warning
    - 7z a -tzip docs.zip doc\_site
    - appveyor PushArtifact docs.zip
    - if defined git_token gh-pages -d doc\_site -m "new docs %GitVersion_FullSemVer%"

# publish NuGet package on tag build
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
deploy:
- provider: NuGet
  api_key:
    secure: OdmGEj/l0K0ZPDmXAYx+fryCzV012eTrM29ALBuL0waxvwLvrufdDXiI+1iNhWEG
  on:
    appveyor_repo_tag: true
